### ISSUE TITLE
Remove Discord Provider

### ISSUE THREAD

**Issue by davidtaing** [davidtaing/bloqcms#8]
Remove the Discord Provider and related enviornment variables from Next-Auth.

**Comment by davidtaing** [comment]
Removing the hacktoberfest fest tag for a minute, so I can setup the CONTRIBUTING.md file. I'll add that back in when I am done.

**Comment by ranaprerna** [comment]
Hey David, can I work on this issue?

**Comment by davidtaing** [comment]
Thanks for reaching out @ranaprerna, I've assigned you to this issue. 

Please let me know if you have any questions.

P.S. Sorry, accidentally assigned myself for a second there.

**Comment by ranaprerna** [comment]
Thank you so much, also by any chance do you plan to add Licence file to the repo?

**Comment by davidtaing** [comment]
That's a good idea. I'll have to think about that, but I'm open to suggestions.

**Comment by davidtaing** [comment]
Adding the hacktoberfest-accepted label just incase. Thanks for the help!

**Comment by ranaprerna** [comment]
Thanks again, David!
